apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
spec:
  predictor:
    serviceAccountName: sa-s3-access
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: "s3://churn-model-bucket-cicd-dimesh/model/model.pkl"
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "2Gi"
